### ISSUE TITLE
get_Cij() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by laurabravopriegue** [diliadis/mlsol#1]
<img width="943" alt="Screenshot 2021-01-29 at 13 29 28" src="https://user-images.githubusercontent.com/24269034/106275382-05ccdc80-6236-11eb-902c-85d15ad6d05e.png">

heya! haven't modified the code at all but im getting this error, any idea why could it be? thanks!!

**Comment by diliadis** [comment]
Hey. Sorry for the late response. It was a small bug. I believe that now it works fine.
